ui:
  default_width: 450
inputs_def:
  - handle: images
    description: Input
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
outputs_def:
  - handle: images
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
    kind: primitive
    nullable: false
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
icon: ":carbon:filter:"
title: Images Filter
